name: ta_lib
description: Dart wrapper of TA-Lib.
version: 0.0.1
repository: https://github.com/kikuchy/ta_lib

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.3
  path: ^1.9.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ffigen: ^16.0.0

ffigen:
  output: 'lib/src/generated_bindings.dart'
  headers:
    entry-points:
      - 'ta-lib/include/ta_func.h'
  silence-enum-warning: true